apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurojobagent
  labels:
    app: eurojobagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurojobagent
  template:
    metadata:
      labels:
        app: eurojobagent
    spec:
      containers:
        - name: eurojobagent
          image: bgdevopsacr2026.azurecr.io/eurojobagent:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TRACKER_JSON_URL
              value: "https://raw.githubusercontent.com/BharadwajGanti-creator/EuroJobAgent/main/tracker.json"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/tracker
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/tracker
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: eurojobagent
spec:
  selector:
    app: eurojobagent
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
